### PR TITLE
Added option to set nCrit

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

I added an option to set `nCrit`. This required setting the `acrit` and `lvconv` variables in Fortran.

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

I added a test similar to the trip location test.

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by eytanadler — COMMENTED** [review]
Fantastic, thank you Sabet! Could you bump the minor or patch version (up to you), since this might be a change that is nice to have an associated version?

Does setting LVCONV to false mean it reinitializes the solution on the next solve? I guess it usually doesn’t matter since it’s only set once at the beginning, but I’m curious if this setup would enable changing ncrit between analyses (which may be unrelated to initializing the solution).

**Comment by sseraj** [comment]
I'm not exactly sure what effect setting LVCONV to False has on the initialization. I was following what the GUI does when setting nCrit:
https://github.com/mdolab/CMPLXFOIL/blob/581dcfddfac2522e94b0b86840c8c46218b04850/src/xoper.f#L599-L605

You're right that it doesn't matter right now because it's only set at the beginning. Changing nCrit (or other Fortran options) between analyses should be possible, but doing this in a user-friendly way would require implementing a `setOption` function like in ADflow that changes the required Fortran variables.

**Review by eytanadler — APPROVED** [review]
I could be wrong, but I think the `setOption` method defined in the `BaseSolver` class that `CMPLXFOIL` inherits is sufficient. We shouldn't need to do anything specific in the Fortran layer since the variable in the Fortran layer gets set every time the solver is called.

Also, I confirmed locally that if you call the solver twice it starts from the previous solution, even when `LVCONV` is set to `False`.

This all looks good to me, thanks again!

**Review by A-CGray — APPROVED** [review]
Nice work, judging from the fortran source, LVCONV is just a convergence flag for the boundary layer solver. So, like @eytanadler said, I don't thinking setting it to false before each call to the solvers should be a problem.

**Comment by sseraj** [comment]
> I could be wrong, but I think the `setOption` method defined in the `BaseSolver` class that `CMPLXFOIL` inherits is sufficient. 

You're right, the Fortran variables are set in `__call__`, so changing nCrit between runs should already work. 

> Also, I confirmed locally that if you call the solver twice it starts from the previous solution, even when LVCONV is set to False.

Thanks for checking the initialization!

**Pull request merged**
