### PR TITLE
Fix crash in fortran layer

### PR DESCRIPTION
**Pull request by eytanadler**
## Purpose

With particularly bad airfoil shapes, the `IBLPAN` function fails. Upon failure, it calls the `STOP` command. This kills not only the XFOIL instance, but also the whole Python script (not good during optimization...).

This PR removes the `STOP` command, instead setting fail flags accordingly and cleanly exiting back to the Python layer.

I also uncommented the residual printout in the real version of CMPLXFOIL so that the user gets some feedback on convergence behavior during the primal solve.

## Expected time until merged

Now!

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by A-CGray** [comment]
Is it at all possible to add a test for this new behaviour? Or is it not possible to recreate a case where `IBLPAN` fails?

**Comment by eytanadler** [comment]
If it ever hits a `STOP` in Fortran, it will kill the program. That means that if the test ever fails, it won't be caught as a test failure and instead will kill the whole testing process. I can probably recreate a case, but if it fails it'll be very difficult to debug. Is that worth it? I think the fact that other regression tests still pass is a good sign that I haven't changed the underlying implementation.

On another note, do you have any idea what's wrong with readthedocs at first glance?

**Review by A-CGray — APPROVED** [review]
LGTM

**Review by hajdik — APPROVED** [review]
Looks good

**Pull request merged**
